numbers=(10,20,30,40,50)
numbers_list=list(numbers)
numbers_list.append(60)
numbers_list[2]=35
print(numbers_list)
numbers=tuple(numbers_list)
print(numbers)

values=(15,5,30,25,10)
values=list(values)
sorted_values=(sorted(values))
print(sorted_values)
final=tuple(sorted_values)
print(final)


fruits=("apple","banana","cherry","banana","mango","banana")
banana_count=fruits.count("banana")
print(banana_count)
fruits=list(fruits)
fruits.remove("banana")
print(fruits)
fruits.remove("banana")
fruits.remove("banana")
print(fruits)

names=("Alice","Bob","Chalie","David")
names=list(names)
names.sort(reverse=True)
print(names)